name: mangasaki
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  desktop: ^5.1.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  encrypt: ^5.0.3
  provider: ^6.0.0
  camera: ^0.11.1
  image_picker: ^1.0.7
  file_picker: ^9.2.1
  universal_platform: ^1.1.0
  flutter_local_notifications: 15.1.1
  windows_notification: ^1.3.0
  permission_handler: ^11.0.0
  device_info_plus: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  web_socket_channel: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.gif
    - assets/images/background2.gif
    - assets/images/logo.png
    - assets/images/background.jpg
    - assets/images/apps.svg
    - assets/images/custom.svg
    - assets/images/social.svg
    - assets/images/stats.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png" # Ruta de tu logo
  adaptive_icon_background: "#ffffff" # Opcional, para Android adaptativo
  adaptive_icon_foreground: "assets/images/logo.png" # Opcional, para Android adaptativo
