name: mangasaki
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  desktop: ^5.1.3
  google_fonts: ^6.2.1
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.gif
    - assets/images/background2.gif
    - assets/images/logo.png
    - assets/images/background.jpg
    - assets/images/apps.svg
    - assets/images/custom.svg
    - assets/images/social.svg
    - assets/images/stats.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png" # Ruta de tu logo
  adaptive_icon_background: "#ffffff" # Opcional, para Android adaptativo
  adaptive_icon_foreground: "assets/images/logo.png" # Opcional, para Android adaptativo
